spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/exampleDatabase?serverTimezone=UTC
    username: root
    password: 145632Aa
    driver: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
  profile:
    active: local

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: health,info